CREATE TABLE addresses (
  address_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id     NUMBER NOT NULL REFERENCES customers(customer_id),
  addr_type       VARCHAR2(20) NOT NULL, -- SHIP / BILL
  line1           VARCHAR2(200) NOT NULL,
  line2           VARCHAR2(200),
  city            VARCHAR2(100) NOT NULL,
  state_code      VARCHAR2(2) NOT NULL,
  postal_code     VARCHAR2(20) NOT NULL,
  country_code    VARCHAR2(2) DEFAULT 'US' NOT NULL,
  is_default      CHAR(1) DEFAULT 'N' NOT NULL,
  created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT addresses_ck1 CHECK (addr_type IN ('SHIP','BILL')),
  CONSTRAINT addresses_ck2 CHECK (is_default IN ('Y','N'))
);
