CREATE TABLE audit_log (
  audit_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type     VARCHAR2(30) NOT NULL,
  entity_id       NUMBER NOT NULL,
  action          VARCHAR2(30) NOT NULL,
  detail          VARCHAR2(4000),
  created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
