CREATE TABLE customers (
  customer_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email           VARCHAR2(255) NOT NULL,
  full_name       VARCHAR2(200) NOT NULL,
  phone           VARCHAR2(40),
  created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  status          VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT customers_u1 UNIQUE (email),
  CONSTRAINT customers_ck1 CHECK (status IN ('ACTIVE','SUSPENDED','DELETED'))
);
