CREATE TABLE discount_rules (
  rule_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_name       VARCHAR2(200) NOT NULL,
  rule_type       VARCHAR2(20) NOT NULL, -- PCT / FIXED
  pct_off         NUMBER(6,4),
  fixed_off       NUMBER(10,2),
  min_subtotal    NUMBER(10,2) DEFAULT 0 NOT NULL,
  category        VARCHAR2(60),
  active_flag     CHAR(1) DEFAULT 'Y' NOT NULL
);
