CREATE TABLE SELECTAI_AGENT.DISCOUNT_RULES (
    RULE_ID NUMBER PRIMARY KEY,
    RULE_TYPE VARCHAR2(20),
    PCT_OFF NUMBER,
    FIXED_OFF NUMBER,
    MIN_SUBTOTAL NUMBER,
    MAX_DISCOUNT NUMBER, -- Added for cap handling
    ACTIVE_FLAG CHAR(1)
);
