CREATE TABLE orders (
  order_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id     NUMBER NOT NULL REFERENCES customers(customer_id),
  ship_address_id NUMBER NOT NULL REFERENCES addresses(address_id),
  bill_address_id NUMBER NOT NULL REFERENCES addresses(address_id),
  status          VARCHAR2(20) DEFAULT 'CART' NOT NULL,
  currency_code   VARCHAR2(3) DEFAULT 'USD' NOT NULL,
  subtotal_amt    NUMBER(12,2) DEFAULT 0 NOT NULL,
  discount_amt    NUMBER(12,2) DEFAULT 0 NOT NULL,
  shipping_amt    NUMBER(12,2) DEFAULT 0 NOT NULL,
  tax_amt         NUMBER(12,2) DEFAULT 0 NOT NULL,
  total_amt       NUMBER(12,2) DEFAULT 0 NOT NULL,
  coupon_code     VARCHAR2(40),
  created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT orders_ck1
    CHECK (status IN ('CART','SUBMITTED','CANCELLED','SHIPPED'))
);
