CREATE TABLE order_adjustments (
  adj_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id        NUMBER NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
  adj_type        VARCHAR2(30) NOT NULL,
  description     VARCHAR2(400),
  amount          NUMBER(12,2) NOT NULL,
  created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
