CREATE TABLE order_items (
  order_item_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id        NUMBER NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
  product_id      NUMBER NOT NULL REFERENCES products(product_id),
  quantity        NUMBER NOT NULL,
  unit_price      NUMBER(10,2) NOT NULL,
  line_subtotal   NUMBER(12,2) NOT NULL,
  is_taxable      CHAR(1) NOT NULL,
  CONSTRAINT order_items_ck1 CHECK (quantity > 0),
  CONSTRAINT order_items_ck2 CHECK (is_taxable IN ('Y','N'))
);
