CREATE TABLE products (
  product_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku             VARCHAR2(40) NOT NULL,
  name            VARCHAR2(200) NOT NULL,
  category        VARCHAR2(60) NOT NULL,
  unit_price      NUMBER(10,2) NOT NULL,
  is_taxable      CHAR(1) DEFAULT 'Y' NOT NULL,
  weight_kg       NUMBER(8,3),
  active_flag     CHAR(1) DEFAULT 'Y' NOT NULL,
  created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT products_u1 UNIQUE (sku),
  CONSTRAINT products_ck1 CHECK (is_taxable IN ('Y','N')),
  CONSTRAINT products_ck2 CHECK (active_flag IN ('Y','N'))
);
